### ISSUE TITLE
can help me ??

### ISSUE THREAD

**Issue by alirezazarghi** [Hasokeyk/instagram#11]
hi me get error
Fatal error: Uncaught Error: Class "Hasokeyk\Instagram\Instagram" not found in D:\xampp\htdocs\Hasokeyk\instagram\examples\user\instagram-user-login.php:10 Stack trace: #0 {main} thrown in D:\xampp\htdocs\Hasokeyk\instagram\examples\user\instagram-user-login.php on line 10
plz help me , thx

**Comment by Nishant8755** [comment]
You download composer
