### ISSUE TITLE
Http 500 Error

### ISSUE THREAD

**Issue by kleisberg** [Hasokeyk/instagram#13]
I'm trying to use the api on my hosting, but I'm getting this error. I wonder what the solution is?

**Comment by Hasokeyk** [comment]
Link atabilir misiniz?

**Comment by kleisberg** [comment]
> Link atabilir misiniz?

https://usmana.ga/hasokeyk/

**Comment by Hasokeyk** [comment]
Php hatalarını aktif ederek deneyebilir misiniz?

```php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

Yukarıdaki kodları index.php nin en başına yazın <?php den sonrasına

**Comment by kleisberg** [comment]
> Php hatalarını aktif ederek deneyebilir misiniz?
> 
> ```
> ini_set('display_errors', 1);
> ini_set('display_startup_errors', 1);
> error_reporting(E_ALL);
> ```
> 
> Yukarıdaki kodları index.php nin en başına yazın <?php den sonrasına

Fatal error: Uncaught Error: Undefined constant "Hasokeyk\Instagram\CURL_HTTP_VERSION_2_0" in /var/www/vhosts/usmana.ga/httpdocs/hasokeyk/vendor/hasokeyk/instagram/src/Instagram/InstagramRequest.php:95 Stack trace: #0 /var/www/vhosts/usmana.ga/httpdocs/hasokeyk/vendor/hasokeyk/instagram/src/Instagram/InstagramLogin.php(156): Hasokeyk\Instagram\InstagramRequest->get() #1 /var/www/vhosts/usmana.ga/httpdocs/hasokeyk/vendor/hasokeyk/instagram/src/Instagram/InstagramLogin.php(57): Hasokeyk\Instagram\InstagramLogin->login_control() #2 /var/www/vhosts/usmana.ga/httpdocs/hasokeyk/index.php(10): Hasokeyk\Instagram\InstagramLogin->login() #3 {main} thrown in /var/www/vhosts/usmana.ga/httpdocs/hasokeyk/vendor/hasokeyk/instagram/src/Instagram/InstagramRequest.php on line 95

**Comment by Hasokeyk** [comment]
Sanırım sunucunuzda curl aktif değil veya php.ini de ki ayarlarında sorun var. 

```php
CURL_HTTP_VERSION_2_0
```

değeri php de hali hazırda kullanılan bir define ama sizde bu define görememiş. 

Php sürümünü 7.4 yapmayı deneyebilirsiniz. 

Zaten 7.4 ise index.php ye 

```php
define('CURL_HTTP_VERSION_2_0',3);
```

yazarak bir test edebilirsiniz.

**Comment by kleisberg** [comment]
define işleminden sonra sorun çözüldü. teşekkürler

**Comment by Hasokeyk** [comment]
Rica ederim iyi çalışmalar 👍🏼
