### ISSUE TITLE
Float Error

### ISSUE THREAD

**Issue by kleisberg** [Hasokeyk/instagram#14]
Dünden beri bu hatayı alıyorum. Girilen userin verilerini çekmeye çalışıyorum fakat karşıma böyle bir hata geliyor bunun sebebi nedir ?

`Deprecated: Implicit conversion from float 5729.84 to int loses precision in /var/www/vhosts/usmana.ga/httpdocs/pp/vendor/hasokeyk/instagram/src/Instagram/InstagramRequest.php on line 349

Deprecated: Implicit conversion from float 5733.75 to int loses precision in /var/www/vhosts/usmana.ga/httpdocs/pp/vendor/hasokeyk/instagram/src/Instagram/InstagramRequest.php on line 321

Deprecated: Implicit conversion from float 5735.66 to int loses precision in /var/www/vhosts/usmana.ga/httpdocs/pp/vendor/hasokeyk/instagram/src/Instagram/InstagramRequest.php on line 293

Deprecated: Implicit conversion from float 5737.54 to int loses precision in /var/www/vhosts/usmana.ga/httpdocs/pp/vendor/hasokeyk/instagram/src/Instagram/InstagramRequest.php on line 377
Login Fail`

**Comment by Hasokeyk** [comment]
Php versiyonunuz nedir?

**Comment by kleisberg** [comment]
> Php versiyonunuz nedir?

8.1.8

**Comment by kleisberg** [comment]
8.1 altı kullandığım zaman hata veriyor php versiyonunuz 8.1 veya üstü olsun diye

**Comment by Hasokeyk** [comment]
Php versiyonunu 7.4 yapabilirseniz, doğru çalışacaktır. Henüz php 8 ve üstü için düzenlemeler yapılmadı.

**Comment by kleisberg** [comment]
> Php versiyonunu 7.4 yapabilirseniz, doğru çalışacaktır. Henüz php 8 ve üstü için düzenlemeler yapılmadı.

7.4.10 yapıyorum fakat 8.1 altı sürüme geçtiğimde şu hatayı alıyorum

Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".

**Comment by Hasokeyk** [comment]
Normalde composer.json da 7.4 e göre ayarlı alttaki linkteki ile aynı olduğunu kontrol ediniz veya kendi composer.json dosyanız varsa ana dizinde oradaki php sürümünü değiştirebilirsiniz. 

https://github.com/Hasokeyk/instagram/blob/main/composer.json

**Comment by kleisberg** [comment]
tamamdır deneyeyim. Size ulaşabileceğim herhangi bir iletişim adresiniz mevcut mudur acaba ? herhangi bir sorunda oradan iletişim kurayım

**Comment by Hasokeyk** [comment]
Telegramdan

@Hasokeyk

Yazarak ulaşabilirsiniz.
