### ISSUE TITLE
Login Fail Hatası 

### ISSUE THREAD

**Issue by yazicii-emre** [Hasokeyk/instagram#15]
Merhabalar,  Kullanıcı adı ve şifre doğru olduğu halde bu hatayı alıyorum sebebi nedir acaba ?

**Comment by Hasokeyk** [comment]
Örnek kodunuzu atabilir misiniz?

**Comment by yazicii-emre** [comment]
<?php

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

use Hasokeyk\Instagram\Instagram;

include "vendor/autoload.php";

$username = 'username';
$password = 'pass';

$instagram = new Instagram($username, $password);

$login = $instagram->login->login_control();
if ($login) {

      $user_posts = $instagram->user->get_user_posts();
      print_r($user_posts);
} else {
      echo 'Login Fail';
}
 
?>

**Comment by Hasokeyk** [comment]
```php

    $instagram = new Instagram($username,$password);
    $login = $instagram->login->login();
    if($login){
        echo 'Login success';
    }else{
       print_r($login);
        echo 'Login Fail';
    }

```

yukarıdaki kodu dener misiniz? Sonucu paylaşırsanız daha iyi yardımcı olabilirim.

**Comment by yazicii-emre** [comment]
Başarılı oldu attığınız kod.

**Comment by Hasokeyk** [comment]
Sizin kodunuzda direkt login kontrol yapmışsınız. Doğal olarak giriş olmadığı için "Login Fail" çıktısını vermiş.

Önce login olmanız sonrasında oturum kontrolü için yolladığınız kodu yollamalısınız.

Örnek Kod
https://github.com/Hasokeyk/instagram#login

**Comment by yazicii-emre** [comment]
Hiç dikkat etmemiştim doğru ya, uzun zaman bilgisayarda uğraşınca böyle oluyor, çok teşekkür ederim.

**Comment by Hasokeyk** [comment]
> Hiç dikkat etmemiştim doğru ya, uzun zaman bilgisayarda uğraşınca böyle oluyor, çok teşekkür ederim.

Sizi çok iyi anlıyorum. 👍🏼 

İyi çalışmalar.
