### ISSUE TITLE
giriş başarısız

### ISSUE THREAD

**Issue by tinerci** [Hasokeyk/instagram#3]
kütüphaneyi denedim fakat şöyle bir hata mevcut, giriş yapmaya çalıştığımda false olarak dönüyor. normal instagram.com dan girdiğimde ise **Yeni bir giriş saptadık, bunu sizmi yaptınız ?** hatası veriyor.

**Comment by Hasokeyk** [comment]
Merhabalar,

instagramda çıkan uyarıya evet bendim derseniz kütüphanede tekrar giriş yaptığınızda sorunsuz bir şekilde giriş yapacaktır.

Karşılaştığınız durum instagramın güvenlik önlemi olduğu için o kısmı bu şekilde geçmeniz gerekiyor.

**Comment by tinerci** [comment]
> Merhabalar,
> 
> instagramda çıkan uyarıya evet bendim derseniz kütüphanede tekrar giriş yaptığınızda sorunsuz bir şekilde giriş yapacaktır.
> 
> Karşılaştığınız durum instagramın güvenlik önlemi olduğu için o kısmı bu şekilde geçmeniz gerekiyor.

Merhaba, SMM Panel üzerinde çalışıyoruz, bu yüzden +500k tek tek giriş yapıp o hatayı evet bendim dersek çok zahmetli olacaktır :)

**Comment by Hasokeyk** [comment]
> > Merhabalar,
> > instagramda çıkan uyarıya evet bendim derseniz kütüphanede tekrar giriş yaptığınızda sorunsuz bir şekilde giriş yapacaktır.
> > Karşılaştığınız durum instagramın güvenlik önlemi olduğu için o kısmı bu şekilde geçmeniz gerekiyor.
> 
> Merhaba, SMM Panel üzerinde çalışıyoruz, bu yüzden +500k tek tek giriş yapıp o hatayı evet bendim dersek çok zahmetli olacaktır :)

Anladım. Bunun için bir araştırma yapmam lazım şu an çözümü bilmiyorum :)

**Comment by tinerci** [comment]
> > > Merhabalar,
> > > instagramda çıkan uyarıya evet bendim derseniz kütüphanede tekrar giriş yaptığınızda sorunsuz bir şekilde giriş yapacaktır.
> > > Karşılaştığınız durum instagramın güvenlik önlemi olduğu için o kısmı bu şekilde geçmeniz gerekiyor.
> > 
> > 
> > Merhaba, SMM Panel üzerinde çalışıyoruz, bu yüzden +500k tek tek giriş yapıp o hatayı evet bendim dersek çok zahmetli olacaktır :)
> 
> Anladım. Bunun için bir araştırma yapmam lazım şu an çözümü bilmiyorum :)

çözüm üretince güncellemeyi haberdar edermisiniz ?

**Comment by Hasokeyk** [comment]
> > > > Merhabalar,
> > > > instagramda çıkan uyarıya evet bendim derseniz kütüphanede tekrar giriş yaptığınızda sorunsuz bir şekilde giriş yapacaktır.
> > > > Karşılaştığınız durum instagramın güvenlik önlemi olduğu için o kısmı bu şekilde geçmeniz gerekiyor.
> > > 
> > > 
> > > Merhaba, SMM Panel üzerinde çalışıyoruz, bu yüzden +500k tek tek giriş yapıp o hatayı evet bendim dersek çok zahmetli olacaktır :)
> > 
> > 
> > Anladım. Bunun için bir araştırma yapmam lazım şu an çözümü bilmiyorum :)
> 
> çözüm üretince güncellemeyi haberdar edermisiniz ?

Tabi ki buradan iletişime geçerim sizinle. Hatta yakında hesap oluşturma fonksiyonunu da eklicem ordan toplu üyelik açabilirsiniz.

**Comment by tinerci** [comment]
> Tabi ki buradan iletişime geçerim sizinle. Hatta yakında hesap oluşturma fonksiyonunu da eklicem ordan toplu üyelik açabilirsiniz.

Merhaba, Bugün öğrendiğim bilgiye göre sanırım bu hatayı Türkiye proxy ile çözüyorlarmış. proxy alanı yaratıp denermisiniz ?

**Comment by Hasokeyk** [comment]
> > Tabi ki buradan iletişime geçerim sizinle. Hatta yakında hesap oluşturma fonksiyonunu da eklicem ordan toplu üyelik açabilirsiniz.
> 
> Merhaba, Bugün öğrendiğim bilgiye göre sanırım bu hatayı Türkiye proxy ile çözüyorlarmış. proxy alanı yaratıp denermisiniz ?

Evet bu konuyu araştırıyorum. Bilgi için teşekkür ederim 👍🏼

**Comment by tinerci** [comment]
> > > Tabi ki buradan iletişime geçerim sizinle. Hatta yakında hesap oluşturma fonksiyonunu da eklicem ordan toplu üyelik açabilirsiniz.
> > 
> > 
> > Merhaba, Bugün öğrendiğim bilgiye göre sanırım bu hatayı Türkiye proxy ile çözüyorlarmış. proxy alanı yaratıp denermisiniz ?
> 
> Evet bu konuyu araştırıyorum. Bilgi için teşekkür ederim 👍🏼

Rica ederim :) Beklemedeyim :)

**Comment by tinerci** [comment]
> Evet bu konuyu araştırıyorum. Bilgi için teşekkür ederim 👍🏼
hocam son durum nedir? güncelleme ne zaman gelir?

**Comment by Hasokeyk** [comment]
Merhabalar,

1-2 güne güncelleme yollayacağım. Proxy olayı dahil :)

**Comment by tinerci** [comment]
> Merhabalar,
> 
> 1-2 güne güncelleme yollayacağım. Proxy olayı dahil :)

Sabırsızlıkla bekliyorum :)

**Comment by erentprt** [comment]
> Merhabalar,
> 
> 1-2 güne güncelleme yollayacağım. Proxy olayı dahil :)

merhabalar giriş hatası alıyorum kullanıcı adı şifre doğru olmasına rağmen

**Comment by tinerci** [comment]
> Merhabalar,
> 
> 1-2 güne güncelleme yollayacağım. Proxy olayı dahil :)

Merhaba, 777 izni olmasına rağmen permission hatası almaktayım
`instagram_request.php on line 89 PHP message: PHP Warning:  mkdir(): Permission denied`

**Comment by Hasokeyk** [comment]
> 

İnstagrama mobilden veya webten giriş yapınca bir uyarı çıkıyor mu? "Yeni bir giriş saptadık" tarzında?

**Comment by Hasokeyk** [comment]
> 

Normalde cache oluştururken 

ANADIZIN/vendor/hasokeyk/instagram/src/cache/

yoluna kayıt eder ama siz bunu 


```
$username = 'username';
$password = 'password';

$instagram = new instagram($username,$password);

//$instagram değişkeninden hemen sonra
$instagram->request->cache_path = 'DOSYAYOLU';
```


Yukarıdaki kodlar ile değiştirebilirsiniz. Yeni oluşturduğunuz klasörüre chmod 777 verip dener misiniz?

**Comment by tinerci** [comment]
> 
> Yukarıdaki kodlar ile değiştirebilirsiniz. Yeni oluşturduğunuz klasörüre chmod 777 verip dener misiniz?

bu şekilde düzeltme yaptım.  **instagram_request.php**

`        public function cache($name, $desc = false, $json = false){
            
            if($this->username != null){
                if(!file_exists($this->cache_path.$this->username)){
                    @mkdir($this->cache_path.$this->username, 0777);
					@chmod($this->cache_path.$this->username, 0777);
                }
                
                if(!file_exists($this->cache_path.$this->username.'/users/')){
                    @mkdir($this->cache_path.$this->username.'/users/', 0777);
					@chmod($this->cache_path.$this->username.'/users/', 0777);
                }
            }
            
            $cache_file_path = $this->cache_path.$this->username.'/';
            $cache_file      = $cache_file_path.($name.'.json');
            
            if(file_exists($cache_file) and time() <= strtotime('+'.$this->cache_time.' minute', filemtime($cache_file))){
                return json_decode(file_get_contents($cache_file));
            }
            else if($desc !== false){
                if($json == true){
                    file_put_contents($cache_file, $desc);
					@chmod($cache_file, 0777);
                }
                else{
                    file_put_contents($cache_file, json_encode($desc));
					@chmod($cache_file, 0777);
                }
                return $desc;
            }
            else{
                return false;
            }
        }`

**Comment by tinerci** [comment]
ek olarak csrftoken.json [null] değeri alıyor.

**Comment by Hasokeyk** [comment]
Merhabalar,

Bir kaç gün sonra bir güncelleme daha çıkıcam. Olmadı sizin pc ye uzaktan bağlanarak sorunu çözmeye çalırız :)

**Comment by tinerci** [comment]
> Merhabalar,
> 
> Bir kaç gün sonra bir güncelleme daha çıkıcam. Olmadı sizin pc ye uzaktan bağlanarak sorunu çözmeye çalırız :)

teşekkürler beklemedeyim :)

**Comment by tinerci** [comment]
Son durum nedir?

**Comment by Hasokeyk** [comment]
Güncellemeyi yayınladım. İşlemleriniz olmazsa bana hasanhasokeyk@hotmail.com dan ulaşabilirsiniz. Uzaktan bağlanarak sorununuzu çözelim.

**Comment by tinerci** [comment]
hocam hiçbir şekilde login olmuyor. error loglardada birşey yok. crfs tokende geliyor şifrede doğru fakat tepki yok. giriş hareketlerindede birşey gözükmemekte

**Comment by Hasokeyk** [comment]
Bana ilettiğim mail ile ulaşabilirseniz bi çözüme ulaştıralım.

**Comment by suphiyasin** [comment]
hocam merhaba kolay gelsin size mail attım acaba müsait zamanınızda bakma şansınız varmıdır?
