### ISSUE TITLE
 Get post info 

### ISSUE THREAD

**Issue by 89z** [Hasokeyk/instagram#5]
If I have a post such as this:

https://www.instagram.com/p/CT-cnxGhvvO/

How do I get the info for this post? Sorry for the basic question, but I have looked over the API and am not seeing a way to do this.

**Comment by Hasokeyk** [comment]
Hi.

What information do you want to receive?

Updates are being made in the library, I can add a list of likes and comments with a single function.

**Comment by 89z** [comment]
I would like to get the images or video files

**Comment by Hasokeyk** [comment]
I will post an update for the download. Stay tuned 😇
