### ISSUE TITLE
güvenliğe düşme sorunu

### ISSUE THREAD

**Issue by tinerci** [Hasokeyk/instagram#6]
Hocam logini var_dump ile çıktı aldım, yurtdışı sunucurında login olunca bunu senmi yaptın sayfasına atıyor. ek çözüm olarak şöyle birşey yaptım fakat çalışmadı.

'X-FB-Client-IP' => 'False',
'X-FB-Client-IP-Forwarded' => '88.255.101.231',

**Comment by tinerci** [comment]
ek olarak proxy kullansakta sunucunun orjinal ip adresini gönderiyor instagrama

**Comment by Hasokeyk** [comment]
Merhabalar,

Bu işlem için bir düzenleme yapıyorum ama hemen bir güncelleme yayınlayamayacağım. Biraz sürer. Kütüphanenin temelinde köklü bir değişiklik olacak. Testleri vs derken 1 ayı bulabilir.

**Comment by tinerci** [comment]
Hocam yapmışken profil bilgileri güncelleme eposta adresi değiştirme, biografi, şifre değiştirme vb işlemleride eklerseniz çok güzel olacak :)

**Comment by Hasokeyk** [comment]
Tamamdır :)

**Comment by tinerci** [comment]
> Tamamdır :)

hocam durumlar nedir? güncelleme gelecekmi?

Gelecekse aşağıdakilerde olursa süper olur.
- Ad soyad, eposta, ,telefon numarası, şifre değiştirme
- Çift faktör kaldırma, Çift faktör ekleme (googleduo)
- like unlike vb.

**Comment by Hasokeyk** [comment]
Merhabalar.

Tüm özelliklerin olduğu ücretli bir sürüm çıkartıyorum.

https://github.com/Hasokeyk/instagram-pro

Detayları yukarıdaki linkten takip edebilirsiniz. Bu repo üzerinden bilgilendirme yapacağım.
