### ISSUE TITLE
Login not working - 'Undefined variable: tag' in openssl_encrypt()

### ISSUE THREAD

**Issue by genisaretskiy** [Hasokeyk/instagram#7]
PHP Notice 'yii\base\ErrorException' with message 'Undefined variable: tag'

in /var/www/html/yii-advanced/vendor/hasokeyk/instagram/src/instagram_login.php:145

**Comment by Hasokeyk** [comment]
Hello,

Which php version are you using?

**Comment by genisaretskiy** [comment]
@Hasokeyk 
PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )

**Comment by Hasokeyk** [comment]
Can you try this solution?

1. Open php.ini file located under php installation folder.
2. Search for extension=php_openssl.dll.
3. Uncomment it by removing the semi-colon(;) in front of it.
4. Restart the Apache Server.

**Comment by genisaretskiy** [comment]
Same error
'Undefined variable: tag'
in /var/www/html/yii-advanced/vendor/hasokeyk/instagram/src/instagram_login.php:145

nano /etc/php/7.0/apache2/php.ini

<img width="618" alt="image" src="https://user-images.githubusercontent.com/12493536/153208121-e40050a3-78ae-4dfd-b767-26a666f52736.png">
sudo service apache2 restart

**Comment by genisaretskiy** [comment]
ok, from PHP 7.4. its working
@Hasokeyk thank you
